### ISSUE TITLE
Shortcut for adding individual track to wishlist

### ISSUE THREAD

**Issue by gunnarvoet** [bamdadsabbagh/bandcamp-plus--extension#104]
Awesome plugin! Would it be possible to add a key shortcut that adds the currently playing song to the wishlist?

**Comment by bamdadsabbagh** [comment]
Hi @gunnarvoet 

Thanks for your suggestion!

Did you have a preferred character in mind ? I added the `W` key for now.

Also, it seems the wishlist function adds the whole release, not only the current track.

As you were very specific in your request, did I miss something about adding only one track to wishlists?

**Comment by gunnarvoet** [comment]
Wow, thanks so much for implementing this! `W` seems like the obvious candidate for this =)

I often add only one track to my wishlist which is a bit cumbersome as I have to click the track that takes me to its own page and there I can add it to the wishlist. If it was possible to just add the currently playing track that would be phenomenal, but I don't know how difficult this would be?

In any case, awesome plugin, thank you so much!

**Comment by bamdadsabbagh** [comment]
I am glad you are liking the extension 😃 

Thanks for explaining how to add a single track, I forgot that page existed! I had a short look over it and I might have a solution...

About the shortcut:

- Is it worth keeping the _add all_ `W`?
- If yes, what do you think of `shift + W`?

**Comment by gunnarvoet** [comment]
Yes, maybe `w` for single track and `W` for the whole album?

**Comment by bamdadsabbagh** [comment]
I added the first draft of the requested feature in the `next/release` branch so you can test it if you want 🤞🏾

Let me know if you need help doing this.

There are some improvements left to do before release:

- Inconsistent rendering when Bandcamp is already playing a track.
	- Steps to reproduce: Load an album, play a track then refresh page.
- When a whole album is added/removed from wishlist, it overwrites the single track wishlisted state.
	- Investigate to prevent overlapping of API requests + view rendering.

**Comment by gunnarvoet** [comment]
Awesome! I would love to try it out. Is it easy to use a feature branch as firefox plugin? I have not done this before.

**Comment by bamdadsabbagh** [comment]
You would need to clone the repo then checkout the `next/release` branch.

With `node` and `yarn` install, you will be able to:

- Run a dedicated firefox or chrome instance with `yarn dev:firefox` or `yarn dev:chrome` accordingly.
	- You would have to login to an account for the feature to be tested
- Or build a zipped package to use with your actual firefox with `yarn build` available in `packages/` then [load a temporary add-on](https://blog.mozilla.org/addons/2015/12/23/loading-temporary-add-ons/)

**Comment by bamdadsabbagh** [comment]
The feature is available in version 3.2.0 🥳

**Comment by bamdadsabbagh** [comment]
The feature is not available for Firefox due to a bug with the AJAX request.

At the moment, only Chrome is supported. I will look into this ASAP.

**Comment by bamdadsabbagh** [comment]
`fetch` in a Firefox Add-on uses the extension's context.

`window.content.fetch` must be used to build a request as if the page was the author.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#xhr_and_fetch

**Comment by gunnarvoet** [comment]
Wow, it works! So awesome, thank you so much!!

**Comment by bamdadsabbagh** [comment]
Awesome! Thanks again for this suggestion, I think it's a killer feature actually 🥇 

Feel free to share the extension around you 😃
