### ISSUE TITLE
extension works only in /track pages

### ISSUE THREAD

**Issue by qweerwat** [bamdadsabbagh/bandcamp-plus--extension#226]
extension works only on /track pages, doesn't appear on /album (no added panels, no shortcuts etc). how to ix this?
![Screenshot_20240317_141826](https://github.com/bamdadsabbagh/bandcamp-plus--extension/assets/100998328/b9059b01-057d-4ce2-94ac-35a19eb3cdfd)
![image](https://github.com/bamdadsabbagh/bandcamp-plus--extension/assets/100998328/0704d30d-9fdd-4ac4-8a49-00f459a7ecdd)

**Comment by bamdadsabbagh** [comment]
Hi @qweerwat,

Thanks for your feedback.

I confirm the issue with the album you linked. I will look into this bug by the end of the week.

For later reference:
- [faulty link](https://zilchpatrol.bandcamp.com/album/zilch-patrol)
- [working link](https://drummy.bandcamp.com/album/galaxy-eaten-ep)
